<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetExt>.gha</TargetExt>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.21.25188.17001" ExcludeAssets="runtime" />
    <ProjectReference Include="..\WeaverBot.Core\WeaverBot.Core.csproj" />
    <EmbeddedResource Include="$(RootDir)media\icon.png" Visible="false" />
  </ItemGroup>

</Project>
